apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: postgres
  template:
    metadata:
      labels:
        components: postgres
    spec:
      containers:
        - name: short-app
          image: postgres:16.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: demo
#          livenessProbe:
#            exec:
#              command:
#                - curl
#                - --fail
#                - http://localhost:3000/api
#              initialDelaySeconds: 30
#              periodSeconds: 5
#              failureThreshold: 1
#          startupProbe:
#            exec:
#              command:
#                - curl
#                - --fail
#                - http://localhost:3000/api
#              initialDelaySeconds: 30
#              periodSeconds: 5
#              failureThreshold: 1
#          readinessProbe:
#            exec:
#              command:
#                - curl
#                - --fail
#                - http://localhost:3000/api
#              initialDelaySeconds: 30
#              periodSeconds: 5
#              failureThreshold: 1

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc